server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.162.40:6033/jiapei?characterEncoding=utf-8
    username: root
    password: 6j3tg3p5a9@0316YTMZZ
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging.level.org.springframework.boot.autoconfigure: ERROR